export default {
	CREATE_STORY_SUCCESS: 'CREATE_STORY_SUCCESS',
	CREATE_STORY_FAILURE: 'CREATE_STORY_FAILURE',
	GET_STORIES_SUCCESS: 'GET_STORIES_SUCCESS',
	GET_STORIES_FAILURE: 'GET_STORIES_FAILURE',
	GET_CURRENT_STORY_SUCCESS: 'GET_CURRENT_STORY_SUCCESS',
	GET_CURRENT_STORY_FAILURE: 'GET_CURRENT_STORY_FAILURE',

}
